"""empty message

Revision ID: 1cb518d3e25c
Revises: 5b50671539c8
Create Date: 2021-01-27 23:21:36.748144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb518d3e25c'
down_revision = '5b50671539c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_on', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
